///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the testRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("518c3ed4-6b26-41e8-978e-0b5b921ca662")]
    public partial class testRepository : RepoGenBaseFolder
    {
        static testRepository instance = new testRepository();
        testRepositoryFolders.INKUBITMicrosoftDynamics365CRMConAppFolder _inkubitmicrosoftdynamics365crmcon;

        /// <summary>
        /// Gets the singleton class instance representing the testRepository element repository.
        /// </summary>
        [RepositoryFolder("518c3ed4-6b26-41e8-978e-0b5b921ca662")]
        public static testRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public testRepository() 
            : base("testRepository", "/", null, 0, false, "518c3ed4-6b26-41e8-978e-0b5b921ca662", ".\\RepositoryImages\\testRepository518c3ed4.rximgres")
        {
            _inkubitmicrosoftdynamics365crmcon = new testRepositoryFolders.INKUBITMicrosoftDynamics365CRMConAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("518c3ed4-6b26-41e8-978e-0b5b921ca662")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The INKUBITMicrosoftDynamics365CRMCon folder.
        /// </summary>
        [RepositoryFolder("0c7eeb3f-3c6d-4058-ab70-3e837820c198")]
        public virtual testRepositoryFolders.INKUBITMicrosoftDynamics365CRMConAppFolder INKUBITMicrosoftDynamics365CRMCon
        {
            get { return _inkubitmicrosoftdynamics365crmcon; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class testRepositoryFolders
    {
        /// <summary>
        /// The INKUBITMicrosoftDynamics365CRMConAppFolder folder.
        /// </summary>
        [RepositoryFolder("0c7eeb3f-3c6d-4058-ab70-3e837820c198")]
        public partial class INKUBITMicrosoftDynamics365CRMConAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _makeuseofthereportingfunctionsandInfo;
            RepoItemInfo _contentInfo;
            RepoItemInfo _blogInfo;
            RepoItemInfo _mainInfo;

            /// <summary>
            /// Creates a new INKUBITMicrosoftDynamics365CRMCon  folder.
            /// </summary>
            public INKUBITMicrosoftDynamics365CRMConAppFolder(RepoGenBaseFolder parentFolder) :
                    base("INKUBITMicrosoftDynamics365CRMCon", "/dom[@domain='www.inkubit.com']", parentFolder, 30000, null, false, "0c7eeb3f-3c6d-4058-ab70-3e837820c198", "")
            {
                _makeuseofthereportingfunctionsandInfo = new RepoItemInfo(this, "MakeUseOfTheReportingFunctionsAnd", ".//div[#'revslider-235']/ul/li[2]/div[1]//p[@innertext~'^Make\\ use\\ of\\ the\\ reporting']", 30000, null, "4cd9cf8a-3761-47b7-81e2-d22b6217989a");
                _contentInfo = new RepoItemInfo(this, "Content", ".//section[#'main']/article", 30000, null, "a0609589-c39d-43a5-9f53-7f25ad7695a3");
                _blogInfo = new RepoItemInfo(this, "Blog", ".//section[#'main']/article/div/div/div/div/h2[@innertext='Blog']", 30000, null, "b38d23f4-1f64-4dc6-a734-275acc5ae562");
                _mainInfo = new RepoItemInfo(this, "Main", ".//section[#'main']", 30000, null, "b00651c1-015f-43ff-b0a9-048255f0ffc3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0c7eeb3f-3c6d-4058-ab70-3e837820c198")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0c7eeb3f-3c6d-4058-ab70-3e837820c198")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MakeUseOfTheReportingFunctionsAnd item.
            /// </summary>
            [RepositoryItem("4cd9cf8a-3761-47b7-81e2-d22b6217989a")]
            public virtual Ranorex.PTag MakeUseOfTheReportingFunctionsAnd
            {
                get
                {
                    return _makeuseofthereportingfunctionsandInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The MakeUseOfTheReportingFunctionsAnd item info.
            /// </summary>
            [RepositoryItemInfo("4cd9cf8a-3761-47b7-81e2-d22b6217989a")]
            public virtual RepoItemInfo MakeUseOfTheReportingFunctionsAndInfo
            {
                get
                {
                    return _makeuseofthereportingfunctionsandInfo;
                }
            }

            /// <summary>
            /// The Content item.
            /// </summary>
            [RepositoryItem("a0609589-c39d-43a5-9f53-7f25ad7695a3")]
            public virtual Ranorex.ArticleTag Content
            {
                get
                {
                    return _contentInfo.CreateAdapter<Ranorex.ArticleTag>(true);
                }
            }

            /// <summary>
            /// The Content item info.
            /// </summary>
            [RepositoryItemInfo("a0609589-c39d-43a5-9f53-7f25ad7695a3")]
            public virtual RepoItemInfo ContentInfo
            {
                get
                {
                    return _contentInfo;
                }
            }

            /// <summary>
            /// The Blog item.
            /// </summary>
            [RepositoryItem("b38d23f4-1f64-4dc6-a734-275acc5ae562")]
            public virtual Ranorex.H2Tag Blog
            {
                get
                {
                    return _blogInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The Blog item info.
            /// </summary>
            [RepositoryItemInfo("b38d23f4-1f64-4dc6-a734-275acc5ae562")]
            public virtual RepoItemInfo BlogInfo
            {
                get
                {
                    return _blogInfo;
                }
            }

            /// <summary>
            /// The Main item.
            /// </summary>
            [RepositoryItem("b00651c1-015f-43ff-b0a9-048255f0ffc3")]
            public virtual Ranorex.SectionTag Main
            {
                get
                {
                    return _mainInfo.CreateAdapter<Ranorex.SectionTag>(true);
                }
            }

            /// <summary>
            /// The Main item info.
            /// </summary>
            [RepositoryItemInfo("b00651c1-015f-43ff-b0a9-048255f0ffc3")]
            public virtual RepoItemInfo MainInfo
            {
                get
                {
                    return _mainInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}