///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace INKUBIT_Test___ContactForm
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CallBack recording.
    /// </summary>
    [TestModule("7caa4df4-0b04-4e47-b3d5-5a8d8bf153ca", ModuleType.Recording, 1)]
    public partial class CallBack : ITestModule
    {
        /// <summary>
        /// Holds an instance of the INKUBIT_Test___ContactFormRepository repository.
        /// </summary>
        public static INKUBIT_Test___ContactFormRepository repo = INKUBIT_Test___ContactFormRepository.Instance;

        static CallBack instance = new CallBack();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CallBack()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CallBack Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://test.inkubit.com/en-us/' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://test.inkubit.com/en-us/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Contact' at 36;19.", repo.INKUBITMicrosoftDynamics365CRMCon.ContactInfo, new RecordItemIndex(2));
            repo.INKUBITMicrosoftDynamics365CRMCon.Contact.Click("36;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.RequestACall' at 27;25.", repo.INKUBITMicrosoftDynamics365CRMCon.RequestACallInfo, new RecordItemIndex(3));
            repo.INKUBITMicrosoftDynamics365CRMCon.RequestACall.Click("27;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.FirstName1' at 116;24.", repo.INKUBITMicrosoftDynamics365CRMCon.FirstName1Info, new RecordItemIndex(4));
            repo.INKUBITMicrosoftDynamics365CRMCon.FirstName1.Click("116;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Ranorex' with focus on 'INKUBITMicrosoftDynamics365CRMCon.FirstName1'.", repo.INKUBITMicrosoftDynamics365CRMCon.FirstName1Info, new RecordItemIndex(5));
            repo.INKUBITMicrosoftDynamics365CRMCon.FirstName1.PressKeys("Ranorex");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.LastName1' at 95;28.", repo.INKUBITMicrosoftDynamics365CRMCon.LastName1Info, new RecordItemIndex(6));
            repo.INKUBITMicrosoftDynamics365CRMCon.LastName1.Click("95;28");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'INKUBITMicrosoftDynamics365CRMCon.LastName1'.", repo.INKUBITMicrosoftDynamics365CRMCon.LastName1Info, new RecordItemIndex(7));
            repo.INKUBITMicrosoftDynamics365CRMCon.LastName1.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.InputPhone' at 78;22.", repo.INKUBITMicrosoftDynamics365CRMCon.InputPhoneInfo, new RecordItemIndex(8));
            repo.INKUBITMicrosoftDynamics365CRMCon.InputPhone.Click("78;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '554455' with focus on 'INKUBITMicrosoftDynamics365CRMCon.InputPhone'.", repo.INKUBITMicrosoftDynamics365CRMCon.InputPhoneInfo, new RecordItemIndex(9));
            repo.INKUBITMicrosoftDynamics365CRMCon.InputPhone.PressKeys("554455");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Text' at 67;28.", repo.INKUBITMicrosoftDynamics365CRMCon.TextInfo, new RecordItemIndex(10));
            repo.INKUBITMicrosoftDynamics365CRMCon.Text.Click("67;28");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '20.12.2019'.", new RecordItemIndex(11));
            Keyboard.Press("20.12.2019");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Afternoon' on item 'INKUBITMicrosoftDynamics365CRMCon.TimeToCall'.", repo.INKUBITMicrosoftDynamics365CRMCon.TimeToCallInfo, new RecordItemIndex(12));
            repo.INKUBITMicrosoftDynamics365CRMCon.TimeToCall.Element.SetAttributeValue("TagValue", "Afternoon");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.InputMessage' at 72;39.", repo.INKUBITMicrosoftDynamics365CRMCon.InputMessageInfo, new RecordItemIndex(13));
            repo.INKUBITMicrosoftDynamics365CRMCon.InputMessage.Click("72;39");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'INKUBITMicrosoftDynamics365CRMCon.InputMessage'.", repo.INKUBITMicrosoftDynamics365CRMCon.InputMessageInfo, new RecordItemIndex(14));
            repo.INKUBITMicrosoftDynamics365CRMCon.InputMessage.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Request' at 15;4.", repo.INKUBITMicrosoftDynamics365CRMCon.RequestInfo, new RecordItemIndex(15));
            repo.INKUBITMicrosoftDynamics365CRMCon.Request.Click("15;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(16));
            Delay.Duration(10000, false);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Thank you for your request. We will contact you as soon as possible.') on item 'INKUBITMicrosoftDynamics365CRMCon.ThankYouForYourRequestWeWillCont'.", repo.INKUBITMicrosoftDynamics365CRMCon.ThankYouForYourRequestWeWillContInfo, new RecordItemIndex(17));
                Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.ThankYouForYourRequestWeWillContInfo, "InnerText", "Thank you for your request. We will contact you as soon as possible.", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(17)); }
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://inkubit-test.crm4.dynamics.com/' with browser 'Chrome' in normal mode.", new RecordItemIndex(18));
            Host.Current.OpenBrowser("https://inkubit-test.crm4.dynamics.com/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(19));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ButBegin' at 57;10.", repo.JobApplicationRanorex1RaTest.ButBeginInfo, new RecordItemIndex(20));
            repo.JobApplicationRanorex1RaTest.ButBegin.Click("57;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(21));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsINKUBITDefaultDashboard.NavTabButtonArrowDownNavTabButtonImageS' at 10;13.", repo.DashboardsINKUBITDefaultDashboard.NavTabButtonArrowDownNavTabButtonImageSInfo, new RecordItemIndex(22));
            repo.DashboardsINKUBITDefaultDashboard.NavTabButtonArrowDownNavTabButtonImageS.Click("10;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(23));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.Activities' at 56;6.", repo.JobApplicationRanorex1RaTest.ActivitiesInfo, new RecordItemIndex(24));
            repo.JobApplicationRanorex1RaTest.Activities.Click("56;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.SelectAView' at 12;11.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.SelectAViewInfo, new RecordItemIndex(25));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.SelectAView.Click("12;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.HttpsInkubitTestCrm4DynamicsCom' at 7;11.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.HttpsInkubitTestCrm4DynamicsComInfo, new RecordItemIndex(26));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.HttpsInkubitTestCrm4DynamicsCom.Click("7;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTest' at 65;8.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTestInfo, new RecordItemIndex(27));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTest.Click("65;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Ranorex test Callback from website requested') on item 'JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTestCallbackFromWebsiteReque'.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTestCallbackFromWebsiteRequeInfo, new RecordItemIndex(28));
            Validate.AttributeEqual(repo.JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTestCallbackFromWebsiteRequeInfo, "InnerText", "Ranorex test Callback from website requested");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTestCallbackFromWebsiteReque' at 126;6.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTestCallbackFromWebsiteRequeInfo, new RecordItemIndex(29));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTestCallbackFromWebsiteReque.Click("126;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(30));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.SpanTagDelete1' at 11;9.", repo.JobApplicationRanorex1RaTest.SpanTagDelete1Info, new RecordItemIndex(31));
            repo.JobApplicationRanorex1RaTest.SpanTagDelete1.Click("11;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(32));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.DivTagDelete' at 41;10.", repo.JobApplicationRanorex1RaTest.DivTagDeleteInfo, new RecordItemIndex(33));
            repo.JobApplicationRanorex1RaTest.DivTagDelete.Click("41;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(34));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'INKUBITMicrosoftDynamics365CRMCon'.", repo.INKUBITMicrosoftDynamics365CRMCon.SelfInfo, new RecordItemIndex(35));
            Host.Current.CloseApplication(repo.INKUBITMicrosoftDynamics365CRMCon.Self, 1000);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'JobApplicationRanorex1RaTest'.", repo.JobApplicationRanorex1RaTest.SelfInfo, new RecordItemIndex(36));
            Host.Current.CloseApplication(repo.JobApplicationRanorex1RaTest.Self, 1000);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
