///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace INKUBIT_Test___ContactForm
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckRecordInCRM recording.
    /// </summary>
    [TestModule("45d55875-8c1f-4c34-a84d-43b29797fbbc", ModuleType.Recording, 1)]
    public partial class CheckRecordInCRM : ITestModule
    {
        /// <summary>
        /// Holds an instance of the INKUBIT_Test___ContactFormRepository repository.
        /// </summary>
        public static INKUBIT_Test___ContactFormRepository repo = INKUBIT_Test___ContactFormRepository.Instance;

        static CheckRecordInCRM instance = new CheckRecordInCRM();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckRecordInCRM()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckRecordInCRM Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://inkubit-test.crm4.dynamics.com' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://inkubit-test.crm4.dynamics.com", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(1));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ButBegin' at 42;12.", repo.JobApplicationRanorex1RaTest.ButBeginInfo, new RecordItemIndex(2));
            repo.JobApplicationRanorex1RaTest.ButBegin.Click("42;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsINKUBITDefaultDashboard.NavTabButtonArrowDownNavTabButtonImageS' at 17;9.", repo.DashboardsINKUBITDefaultDashboard.NavTabButtonArrowDownNavTabButtonImageSInfo, new RecordItemIndex(3));
            repo.DashboardsINKUBITDefaultDashboard.NavTabButtonArrowDownNavTabButtonImageS.Click("17;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(4));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.HttpsInkubitTestCrm4DynamicsComP' at 23;12.", repo.JobApplicationRanorex1RaTest.HttpsInkubitTestCrm4DynamicsComPInfo, new RecordItemIndex(5));
            repo.JobApplicationRanorex1RaTest.HttpsInkubitTestCrm4DynamicsComP.Click("23;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(6));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.CreatedOn' at 36;11.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.CreatedOnInfo, new RecordItemIndex(7));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.CreatedOn.Click("36;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(8));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.CreatedOn' at 36;11.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.CreatedOnInfo, new RecordItemIndex(9));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.CreatedOn.Click("36;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(10));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.ATag1227201865244PMRanorexStudi' at 129;7.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.ATag1227201865244PMRanorexStudiInfo, new RecordItemIndex(11));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.ATag1227201865244PMRanorexStudi.Click("129;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(12));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='ranorex.studio@gmail.com') on item 'JobApplicationRanorex1RaTest.ContentIFrame1.RanorexStudioAtgmailCom'.", repo.JobApplicationRanorex1RaTest.ContentIFrame1.RanorexStudioAtgmailComInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.JobApplicationRanorex1RaTest.ContentIFrame1.RanorexStudioAtgmailComInfo, "InnerText", "ranorex.studio@gmail.com");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.SpanTagDelete3' at 23;14.", repo.JobApplicationRanorex1RaTest.SpanTagDelete3Info, new RecordItemIndex(14));
            repo.JobApplicationRanorex1RaTest.SpanTagDelete3.Click("23;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(15));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.DivTagDelete' at 40;7.", repo.JobApplicationRanorex1RaTest.DivTagDeleteInfo, new RecordItemIndex(16));
            repo.JobApplicationRanorex1RaTest.DivTagDelete.Click("40;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(17));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'JobApplicationRanorex1RaTest'.", repo.JobApplicationRanorex1RaTest.SelfInfo, new RecordItemIndex(18));
            Host.Current.CloseApplication(repo.JobApplicationRanorex1RaTest.Self, 1000);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
