///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace INKUBIT_Test___ContactForm
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Check_Career_Test recording.
    /// </summary>
    [TestModule("a9d4027f-4759-4c9d-9921-66e2b39b7ef5", ModuleType.Recording, 1)]
    public partial class Check_Career_Test : ITestModule
    {
        /// <summary>
        /// Holds an instance of the INKUBIT_Test___ContactFormRepository repository.
        /// </summary>
        public static INKUBIT_Test___ContactFormRepository repo = INKUBIT_Test___ContactFormRepository.Instance;

        static Check_Career_Test instance = new Check_Career_Test();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Check_Career_Test()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Check_Career_Test Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://test.inkubit.com/en-us/careers/' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://test.inkubit.com/en-us/careers/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PanelBody.SeniorSAPHCMConsultant' at 89;7.", repo.INKUBITMicrosoftDynamics365CRMCon.PanelBody.SeniorSAPHCMConsultantInfo, new RecordItemIndex(2));
            repo.INKUBITMicrosoftDynamics365CRMCon.PanelBody.SeniorSAPHCMConsultant.Click("89;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Senior SAP HCM Consultant') on item 'INKUBITMicrosoftDynamics365CRMCon.SeniorSAPHCMConsultant'.", repo.INKUBITMicrosoftDynamics365CRMCon.SeniorSAPHCMConsultantInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.SeniorSAPHCMConsultantInfo, "InnerText", "Senior SAP HCM Consultant");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PageBox.Careers1' at 21;3.", repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.Careers1Info, new RecordItemIndex(4));
            repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.Careers1.Click("21;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2ms.", new RecordItemIndex(5));
            Delay.Duration(2, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PanelBody.SAPSeniorBusinessIntelligenceConsult' at 170;8.", repo.INKUBITMicrosoftDynamics365CRMCon.PanelBody.SAPSeniorBusinessIntelligenceConsultInfo, new RecordItemIndex(6));
            repo.INKUBITMicrosoftDynamics365CRMCon.PanelBody.SAPSeniorBusinessIntelligenceConsult.Click("170;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='SAP Senior Business Intelligence Consultant') on item 'INKUBITMicrosoftDynamics365CRMCon.SAPSeniorBusinessIntelligenceConsult'.", repo.INKUBITMicrosoftDynamics365CRMCon.SAPSeniorBusinessIntelligenceConsultInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.SAPSeniorBusinessIntelligenceConsultInfo, "InnerText", "SAP Senior Business Intelligence Consultant");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PageBox.Careers1' at 18;7.", repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.Careers1Info, new RecordItemIndex(9));
            repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.Careers1.Click("18;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(10));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(11));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PanelBody.SAPSeniorBankingConsultant' at 196;5.", repo.INKUBITMicrosoftDynamics365CRMCon.PanelBody.SAPSeniorBankingConsultantInfo, new RecordItemIndex(12));
            repo.INKUBITMicrosoftDynamics365CRMCon.PanelBody.SAPSeniorBankingConsultant.Click("196;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(13));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='SAP Senior Banking Consultant') on item 'INKUBITMicrosoftDynamics365CRMCon.SAPSeniorBankingConsultant'.", repo.INKUBITMicrosoftDynamics365CRMCon.SAPSeniorBankingConsultantInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.SAPSeniorBankingConsultantInfo, "InnerText", "SAP Senior Banking Consultant");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PageBox.Careers1' at 20;7.", repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.Careers1Info, new RecordItemIndex(15));
            repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.Careers1.Click("20;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(16));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag' at 19;17.", repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.ATagInfo, new RecordItemIndex(17));
            repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag.Click("19;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PageBox.JuniorMicrosoftDynamics365Developer' at 164;8.", repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.JuniorMicrosoftDynamics365DeveloperInfo, new RecordItemIndex(18));
            repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.JuniorMicrosoftDynamics365Developer.Click("164;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Junior Microsoft Dynamics 365 Developer') on item 'INKUBITMicrosoftDynamics365CRMCon.JuniorMicrosoftDynamics365Developer'.", repo.INKUBITMicrosoftDynamics365CRMCon.JuniorMicrosoftDynamics365DeveloperInfo, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.JuniorMicrosoftDynamics365DeveloperInfo, "InnerText", "Junior Microsoft Dynamics 365 Developer");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.SoftwareEngineering' at 74;8.", repo.INKUBITMicrosoftDynamics365CRMCon.SoftwareEngineeringInfo, new RecordItemIndex(20));
            repo.INKUBITMicrosoftDynamics365CRMCon.SoftwareEngineering.Click("74;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PageBox.JuniorMicrosoftBusinessIntelligenceD' at 273;13.", repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.JuniorMicrosoftBusinessIntelligenceDInfo, new RecordItemIndex(21));
            repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.JuniorMicrosoftBusinessIntelligenceD.Click("273;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Junior Microsoft Business Intelligence Developer') on item 'INKUBITMicrosoftDynamics365CRMCon.JuniorMicrosoftBusinessIntelligenceD'.", repo.INKUBITMicrosoftDynamics365CRMCon.JuniorMicrosoftBusinessIntelligenceDInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.JuniorMicrosoftBusinessIntelligenceDInfo, "InnerText", "Junior Microsoft Business Intelligence Developer");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.SoftwareEngineering' at 71;7.", repo.INKUBITMicrosoftDynamics365CRMCon.SoftwareEngineeringInfo, new RecordItemIndex(23));
            repo.INKUBITMicrosoftDynamics365CRMCon.SoftwareEngineering.Click("71;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(24));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.JuniorMicrosoftASPNetFullStackDeve' at 292;15.", repo.INKUBITMicrosoftDynamics365CRMCon.JuniorMicrosoftASPNetFullStackDeveInfo, new RecordItemIndex(25));
            repo.INKUBITMicrosoftDynamics365CRMCon.JuniorMicrosoftASPNetFullStackDeve.Click("292;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Junior Microsoft ASP.Net Full-Stack Developer') on item 'INKUBITMicrosoftDynamics365CRMCon.JuniorMicrosoftASPNetFullStackDeve1'.", repo.INKUBITMicrosoftDynamics365CRMCon.JuniorMicrosoftASPNetFullStackDeve1Info, new RecordItemIndex(26));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.JuniorMicrosoftASPNetFullStackDeve1Info, "InnerText", "Junior Microsoft ASP.Net Full-Stack Developer");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.SoftwareEngineering' at 71;8.", repo.INKUBITMicrosoftDynamics365CRMCon.SoftwareEngineeringInfo, new RecordItemIndex(27));
            repo.INKUBITMicrosoftDynamics365CRMCon.SoftwareEngineering.Click("71;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag1' at 13;22.", repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag1Info, new RecordItemIndex(28));
            repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag1.Click("13;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag2' at 19;9.", repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag2Info, new RecordItemIndex(29));
            repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag2.Click("19;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.ATagJuniorProjectManagementOffice' at 222;10.", repo.INKUBITMicrosoftDynamics365CRMCon.ATagJuniorProjectManagementOfficeInfo, new RecordItemIndex(30));
            repo.INKUBITMicrosoftDynamics365CRMCon.ATagJuniorProjectManagementOffice.Click("222;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='(Junior-) Project Management Office and Administrative Assistance') on item 'INKUBITMicrosoftDynamics365CRMCon.H1TagJuniorProjectManagementOffice'.", repo.INKUBITMicrosoftDynamics365CRMCon.H1TagJuniorProjectManagementOfficeInfo, new RecordItemIndex(31));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.H1TagJuniorProjectManagementOfficeInfo, "InnerText", "(Junior-) Project Management Office and Administrative Assistance");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PageBox.Administration' at 39;7.", repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.AdministrationInfo, new RecordItemIndex(32));
            repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.Administration.Click("39;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag2' at 19;14.", repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag2Info, new RecordItemIndex(33));
            repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag2.Click("19;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag3' at 19;16.", repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag3Info, new RecordItemIndex(34));
            repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag3.Click("19;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.ATagJuniorAccountManager' at 122;5.", repo.INKUBITMicrosoftDynamics365CRMCon.ATagJuniorAccountManagerInfo, new RecordItemIndex(35));
            repo.INKUBITMicrosoftDynamics365CRMCon.ATagJuniorAccountManager.Click("122;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='(Junior-) Account Manager') on item 'INKUBITMicrosoftDynamics365CRMCon.H1TagJuniorAccountManager'.", repo.INKUBITMicrosoftDynamics365CRMCon.H1TagJuniorAccountManagerInfo, new RecordItemIndex(36));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.H1TagJuniorAccountManagerInfo, "InnerText", "(Junior-) Account Manager");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PageBox.Sales' at 20;8.", repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.SalesInfo, new RecordItemIndex(37));
            repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.Sales.Click("20;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag3' at 25;19.", repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag3Info, new RecordItemIndex(38));
            repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag3.Click("25;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag4' at 22;21.", repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag4Info, new RecordItemIndex(39));
            repo.INKUBITMicrosoftDynamics365CRMCon.PageBox.ATag4.Click("22;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.ATagJuniorHRSpecialistGlobalRecru' at 170;9.", repo.INKUBITMicrosoftDynamics365CRMCon.ATagJuniorHRSpecialistGlobalRecruInfo, new RecordItemIndex(40));
            repo.INKUBITMicrosoftDynamics365CRMCon.ATagJuniorHRSpecialistGlobalRecru.Click("170;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='(Junior-) HR Specialist Global Recruiting') on item 'INKUBITMicrosoftDynamics365CRMCon.H1TagJuniorHRSpecialistGlobalRecr'.", repo.INKUBITMicrosoftDynamics365CRMCon.H1TagJuniorHRSpecialistGlobalRecrInfo, new RecordItemIndex(41));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.H1TagJuniorHRSpecialistGlobalRecrInfo, "InnerText", "(Junior-) HR Specialist Global Recruiting");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
