///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace INKUBIT_Test___ContactForm
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ContactFormRecord recording.
    /// </summary>
    [TestModule("512bb11f-e11f-45a1-a5de-127587ad28df", ModuleType.Recording, 1)]
    public partial class ContactFormRecord : ITestModule
    {
        /// <summary>
        /// Holds an instance of the INKUBIT_Test___ContactFormRepository repository.
        /// </summary>
        public static INKUBIT_Test___ContactFormRepository repo = INKUBIT_Test___ContactFormRepository.Instance;

        static ContactFormRecord instance = new ContactFormRecord();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ContactFormRecord()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ContactFormRecord Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://test.inkubit.com/en-us/' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://test.inkubit.com/en-us/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Contact' at 35;21.", repo.INKUBITMicrosoftDynamics365CRMCon.ContactInfo, new RecordItemIndex(2));
            repo.INKUBITMicrosoftDynamics365CRMCon.Contact.Click("35;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.FirstName1' at 95;17.", repo.INKUBITMicrosoftDynamics365CRMCon.FirstName1Info, new RecordItemIndex(3));
            repo.INKUBITMicrosoftDynamics365CRMCon.FirstName1.Click("95;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ranorex' with focus on 'INKUBITMicrosoftDynamics365CRMCon.FirstName1'.", repo.INKUBITMicrosoftDynamics365CRMCon.FirstName1Info, new RecordItemIndex(4));
            repo.INKUBITMicrosoftDynamics365CRMCon.FirstName1.PressKeys("ranorex");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.LastName1' at 96;21.", repo.INKUBITMicrosoftDynamics365CRMCon.LastName1Info, new RecordItemIndex(5));
            repo.INKUBITMicrosoftDynamics365CRMCon.LastName1.Click("96;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'INKUBITMicrosoftDynamics365CRMCon.LastName1'.", repo.INKUBITMicrosoftDynamics365CRMCon.LastName1Info, new RecordItemIndex(6));
            repo.INKUBITMicrosoftDynamics365CRMCon.LastName1.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.InputEmail' at 60;26.", repo.INKUBITMicrosoftDynamics365CRMCon.InputEmailInfo, new RecordItemIndex(7));
            repo.INKUBITMicrosoftDynamics365CRMCon.InputEmail.Click("60;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'te' with focus on 'INKUBITMicrosoftDynamics365CRMCon.InputEmail'.", repo.INKUBITMicrosoftDynamics365CRMCon.InputEmailInfo, new RecordItemIndex(8));
            repo.INKUBITMicrosoftDynamics365CRMCon.InputEmail.PressKeys("te");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'st{LShiftKey down}@{LShiftKey up}123' with focus on 'INKUBITMicrosoftDynamics365CRMCon.InputEmail'.", repo.INKUBITMicrosoftDynamics365CRMCon.InputEmailInfo, new RecordItemIndex(9));
            repo.INKUBITMicrosoftDynamics365CRMCon.InputEmail.PressKeys("st{LShiftKey down}@{LShiftKey up}123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.' with focus on 'INKUBITMicrosoftDynamics365CRMCon.InputEmail'.", repo.INKUBITMicrosoftDynamics365CRMCon.InputEmailInfo, new RecordItemIndex(10));
            repo.INKUBITMicrosoftDynamics365CRMCon.InputEmail.PressKeys(".");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'pl' with focus on 'INKUBITMicrosoftDynamics365CRMCon.InputEmail'.", repo.INKUBITMicrosoftDynamics365CRMCon.InputEmailInfo, new RecordItemIndex(11));
            repo.INKUBITMicrosoftDynamics365CRMCon.InputEmail.PressKeys("pl");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.InputMessage' at 87;23.", repo.INKUBITMicrosoftDynamics365CRMCon.InputMessageInfo, new RecordItemIndex(12));
            repo.INKUBITMicrosoftDynamics365CRMCon.InputMessage.Click("87;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'INKUBITMicrosoftDynamics365CRMCon.InputMessage'.", repo.INKUBITMicrosoftDynamics365CRMCon.InputMessageInfo, new RecordItemIndex(13));
            repo.INKUBITMicrosoftDynamics365CRMCon.InputMessage.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.SEND' at 17;12.", repo.INKUBITMicrosoftDynamics365CRMCon.SENDInfo, new RecordItemIndex(14));
            repo.INKUBITMicrosoftDynamics365CRMCon.SEND.Click("17;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(15));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Thank you for your message. We will contact you shortly.') on item 'INKUBITMicrosoftDynamics365CRMCon.ThankYouForYourMessageWeWillCont1'.", repo.INKUBITMicrosoftDynamics365CRMCon.ThankYouForYourMessageWeWillCont1Info, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.ThankYouForYourMessageWeWillCont1Info, "InnerText", "Thank you for your message. We will contact you shortly.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://inkubit-test.crm4.dynamics.com/main.aspx#143771525' with browser 'Chrome' in normal mode.", new RecordItemIndex(17));
            Host.Current.OpenBrowser("https://inkubit-test.crm4.dynamics.com/main.aspx#143771525", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(18));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ButBegin' at 32;13.", repo.JobApplicationRanorex1RaTest.ButBeginInfo, new RecordItemIndex(19));
            repo.JobApplicationRanorex1RaTest.ButBegin.Click("32;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.TabMA' at 17;28.", repo.JobApplicationRanorex1RaTest.TabMAInfo, new RecordItemIndex(20));
            repo.JobApplicationRanorex1RaTest.TabMA.Click("17;28");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.Activities' at 70;8.", repo.JobApplicationRanorex1RaTest.ActivitiesInfo, new RecordItemIndex(21));
            repo.JobApplicationRanorex1RaTest.Activities.Click("70;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.SelectAView' at 12;15.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.SelectAViewInfo, new RecordItemIndex(22));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.SelectAView.Click("12;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.HttpsInkubitTestCrm4DynamicsCom' at 4;6.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.HttpsInkubitTestCrm4DynamicsComInfo, new RecordItemIndex(23));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.HttpsInkubitTestCrm4DynamicsCom.Click("4;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.Nobr' at 103;14.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.NobrInfo, new RecordItemIndex(24));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.Nobr.Click("103;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(25));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTestEmailContactFromWebsite' at 86;5.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTestEmailContactFromWebsiteInfo, new RecordItemIndex(26));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTestEmailContactFromWebsite.Click("86;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(27));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=' ranorex test') on item 'JobApplicationRanorex1RaTest.ContentIFrame1.RegardingobjectidLookupValue'.", repo.JobApplicationRanorex1RaTest.ContentIFrame1.RegardingobjectidLookupValueInfo, new RecordItemIndex(28));
            Validate.AttributeEqual(repo.JobApplicationRanorex1RaTest.ContentIFrame1.RegardingobjectidLookupValueInfo, "InnerText", " ranorex test");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.SpanTagDelete1' at 6;5.", repo.JobApplicationRanorex1RaTest.SpanTagDelete1Info, new RecordItemIndex(29));
            repo.JobApplicationRanorex1RaTest.SpanTagDelete1.Click("6;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(30));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.DivTagDelete' at 38;9.", repo.JobApplicationRanorex1RaTest.DivTagDeleteInfo, new RecordItemIndex(31));
            repo.JobApplicationRanorex1RaTest.DivTagDelete.Click("38;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(32));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'INKUBITMicrosoftDynamics365CRMCon'.", repo.INKUBITMicrosoftDynamics365CRMCon.SelfInfo, new RecordItemIndex(33));
            Host.Current.CloseApplication(repo.INKUBITMicrosoftDynamics365CRMCon.Self, 1000);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'JobApplicationRanorex1RaTest'.", repo.JobApplicationRanorex1RaTest.SelfInfo, new RecordItemIndex(34));
            Host.Current.CloseApplication(repo.JobApplicationRanorex1RaTest.Self, 1000);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
