///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace INKUBIT_Test___ContactForm
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The en_website recording.
    /// </summary>
    [TestModule("c1aa053e-d7dd-4371-be64-36e5d4770c26", ModuleType.Recording, 1)]
    public partial class en_website : ITestModule
    {
        /// <summary>
        /// Holds an instance of the INKUBIT_Test___ContactFormRepository repository.
        /// </summary>
        public static INKUBIT_Test___ContactFormRepository repo = INKUBIT_Test___ContactFormRepository.Instance;

        static en_website instance = new en_website();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public en_website()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static en_website Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.inkubit.com/en-us/' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://www.inkubit.com/en-us/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Height='52') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.HttpsWwwInkubitComMedia45350Inku'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.HttpsWwwInkubitComMedia45350InkuInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.HttpsWwwInkubitComMedia45350InkuInfo, "Height", "52");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Hspace='0') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.HttpsWwwInkubitComMedia45350Inku'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.HttpsWwwInkubitComMedia45350InkuInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.HttpsWwwInkubitComMedia45350InkuInfo, "Hspace", "0");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='https://www.inkubit.com/media/45350/inkubit_logo_small-mit-schriftzug.png') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.HttpsWwwInkubitComMedia45350Inku'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.HttpsWwwInkubitComMedia45350InkuInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.HttpsWwwInkubitComMedia45350InkuInfo, "Src", "https://www.inkubit.com/media/45350/inkubit_logo_small-mit-schriftzug.png");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Width='250') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.HttpsWwwInkubitComMedia45350Inku'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.HttpsWwwInkubitComMedia45350InkuInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.HttpsWwwInkubitComMedia45350InkuInfo, "Width", "250");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://www.inkubit.com/en-us/') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.Home'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.HomeInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.HomeInfo, "Href", "https://www.inkubit.com/en-us/");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='About INKUBIT') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.AboutINKUBIT'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.AboutINKUBITInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.AboutINKUBITInfo, "InnerText", "About INKUBIT");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://www.inkubit.com/en-us/#') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.AboutINKUBIT'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.AboutINKUBITInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.AboutINKUBITInfo, "Href", "https://www.inkubit.com/en-us/#");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Solutions & Services') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.SolutionsServices'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.SolutionsServicesInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.SolutionsServicesInfo, "InnerText", "Solutions & Services");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://www.inkubit.com/en-us/#') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.SolutionsServices'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.SolutionsServicesInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.SolutionsServicesInfo, "Href", "https://www.inkubit.com/en-us/#");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Blog') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.Blog'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.BlogInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.BlogInfo, "InnerText", "Blog");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://www.inkubit.com/en-us/blog/') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.Blog'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.BlogInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.BlogInfo, "Href", "https://www.inkubit.com/en-us/blog/");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Customers') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.Customers'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.CustomersInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.CustomersInfo, "InnerText", "Customers");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://www.inkubit.com/en-us/#') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.Customers'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.CustomersInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.CustomersInfo, "Href", "https://www.inkubit.com/en-us/#");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Contact') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.Contact'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.ContactInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.ContactInfo, "InnerText", "Contact");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://www.inkubit.com/en-us/#') on item 'HttpsWwwInkubitComEnUsCareers.SomeDivTag.Contact'.", repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.ContactInfo, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeDivTag.ContactInfo, "Href", "https://www.inkubit.com/en-us/#");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Microsoft Dynamics 365 offers high-performance Marketing. Sales- and Service-Tools to improve productivity and increase turnover.') on item 'HttpsWwwInkubitComEnUsCareers.Revslider696.MicrosoftDynamics365OffersHighPerfo'.", repo.HttpsWwwInkubitComEnUsCareers.Revslider696.MicrosoftDynamics365OffersHighPerfoInfo, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.Revslider696.MicrosoftDynamics365OffersHighPerfoInfo, "InnerText", "Microsoft Dynamics 365 offers high-performance Marketing. Sales- and Service-Tools to improve productivity and increase turnover.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Azure is a comprehensive set of cloud services that developers and IT professionals use to build, deploy, and manage applications through our global network of datacenters. Integrated tools, DevOps, and a marketplace support you in efficiently building anything from simple mobile apps to internet-scale solutions') on item 'HttpsWwwInkubitComEnUsCareers.Revslider696.AzureIsAComprehensiveSetOfCloudSe'.", repo.HttpsWwwInkubitComEnUsCareers.Revslider696.AzureIsAComprehensiveSetOfCloudSeInfo, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.Revslider696.AzureIsAComprehensiveSetOfCloudSeInfo, "InnerText", "Azure is a comprehensive set of cloud services that developers and IT professionals use to build, deploy, and manage applications through our global network of datacenters. Integrated tools, DevOps, and a marketplace support you in efficiently building anything from simple mobile apps to internet-scale solutions");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='SharePoint is an integrated document management tool, which can easily be adminstrated and ensures a high level of data integrity.') on item 'HttpsWwwInkubitComEnUsCareers.Revslider696.SharePointIsAnIntegratedDocumentMan'.", repo.HttpsWwwInkubitComEnUsCareers.Revslider696.SharePointIsAnIntegratedDocumentManInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.Revslider696.SharePointIsAnIntegratedDocumentManInfo, "InnerText", "SharePoint is an integrated document management tool, which can easily be adminstrated and ensures a high level of data integrity.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Use a variatey of tools within the Office suite to mangage, create and share documents and support internal communication. With the Office Apps Users can access the Office Suite anywhere and anytime. ') on item 'HttpsWwwInkubitComEnUsCareers.Revslider696.UseAVariateyOfToolsWithinTheOffic'.", repo.HttpsWwwInkubitComEnUsCareers.Revslider696.UseAVariateyOfToolsWithinTheOfficInfo, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.Revslider696.UseAVariateyOfToolsWithinTheOfficInfo, "InnerText", "Use a variatey of tools within the Office suite to mangage, create and share documents and support internal communication. With the Office Apps Users can access the Office Suite anywhere and anytime. ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='img') on item 'HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74145Logo'.", repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74145LogoInfo, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74145LogoInfo, "TagName", "img");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Height='39') on item 'HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74145Logo'.", repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74145LogoInfo, new RecordItemIndex(21));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74145LogoInfo, "Height", "39");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='https://www.inkubit.com/media/74145/logo_inkubit.png') on item 'HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74145Logo'.", repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74145LogoInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74145LogoInfo, "Src", "https://www.inkubit.com/media/74145/logo_inkubit.png");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='img') on item 'HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia75028Try3'.", repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia75028Try3Info, new RecordItemIndex(23));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia75028Try3Info, "TagName", "img");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Height='63') on item 'HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia75028Try3'.", repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia75028Try3Info, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia75028Try3Info, "Height", "63");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='https://www.inkubit.com/media/75028/try3.png') on item 'HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia75028Try3'.", repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia75028Try3Info, new RecordItemIndex(25));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia75028Try3Info, "Src", "https://www.inkubit.com/media/75028/try3.png");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='img') on item 'HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74152Logo'.", repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74152LogoInfo, new RecordItemIndex(26));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74152LogoInfo, "TagName", "img");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Height='23') on item 'HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74152Logo'.", repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74152LogoInfo, new RecordItemIndex(27));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74152LogoInfo, "Height", "23");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='https://www.inkubit.com/media/74152/logo2.png') on item 'HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74152Logo'.", repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74152LogoInfo, new RecordItemIndex(28));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.SomeUlTag.HttpsWwwInkubitComMedia74152LogoInfo, "Src", "https://www.inkubit.com/media/74152/logo2.png");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://www.xing.com/companies/inkubit') on item 'HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpsWwwXingComCompaniesInkubit'.", repo.HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpsWwwXingComCompaniesInkubitInfo, new RecordItemIndex(29));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpsWwwXingComCompaniesInkubitInfo, "Href", "https://www.xing.com/companies/inkubit");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://www.linkedin.com/company/inkubit/') on item 'HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpsWwwLinkedinComCompanyInkubit'.", repo.HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpsWwwLinkedinComCompanyInkubitInfo, new RecordItemIndex(30));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpsWwwLinkedinComCompanyInkubitInfo, "Href", "https://www.linkedin.com/company/inkubit/");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='http://twitter.com/inkubit') on item 'HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpTwitterComInkubit'.", repo.HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpTwitterComInkubitInfo, new RecordItemIndex(31));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpTwitterComInkubitInfo, "Href", "http://twitter.com/inkubit");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='http://www.facebook.com/inkubit') on item 'HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpWwwFacebookComInkubit'.", repo.HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpWwwFacebookComInkubitInfo, new RecordItemIndex(32));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpWwwFacebookComInkubitInfo, "Href", "http://www.facebook.com/inkubit");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://www.instagram.com/inkubit/') on item 'HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpsWwwInstagramComInkubit'.", repo.HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpsWwwInstagramComInkubitInfo, new RecordItemIndex(33));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpsWwwInstagramComInkubitInfo, "Href", "https://www.instagram.com/inkubit/");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://www.kununu.com/de/inkubit') on item 'HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpsWwwKununuComDeInkubit'.", repo.HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpsWwwKununuComDeInkubitInfo, new RecordItemIndex(34));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.RowSidebar.HttpsWwwKununuComDeInkubitInfo, "Href", "https://www.kununu.com/de/inkubit");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='https://www.inkubit.com/Assets/frontend/img/email.png') on item 'HttpsWwwInkubitComEnUsCareers.EmailMesessage'.", repo.HttpsWwwInkubitComEnUsCareers.EmailMesessageInfo, new RecordItemIndex(35));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.EmailMesessageInfo, "Src", "https://www.inkubit.com/Assets/frontend/img/email.png");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
