///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace INKUBIT_Test___ContactForm
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LandingPage recording.
    /// </summary>
    [TestModule("aef84a13-3177-48f8-a4c4-9e26916ea3b5", ModuleType.Recording, 1)]
    public partial class LandingPage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the INKUBIT_Test___ContactFormRepository repository.
        /// </summary>
        public static INKUBIT_Test___ContactFormRepository repo = INKUBIT_Test___ContactFormRepository.Instance;

        static LandingPage instance = new LandingPage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LandingPage()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LandingPage Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://test.inkubit.com/en-us/tomaszdontremove/' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://test.inkubit.com/en-us/tomaszdontremove/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.ContactForm1.ContactForm' at 536;17.", repo.INKUBITMicrosoftDynamics365CRMCon.ContactForm1.ContactFormInfo, new RecordItemIndex(2));
            repo.INKUBITMicrosoftDynamics365CRMCon.ContactForm1.ContactForm.Click("536;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(3));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ranorex{Tab}ra{Tab}123{RShiftKey down}@{RShiftKey up}123.pl{Tab}test'.", new RecordItemIndex(4));
            Keyboard.Press("ranorex{Tab}ra{Tab}123{RShiftKey down}@{RShiftKey up}123.pl{Tab}test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.ContactForm1.SEND1' at 37;26.", repo.INKUBITMicrosoftDynamics365CRMCon.ContactForm1.SEND1Info, new RecordItemIndex(5));
            repo.INKUBITMicrosoftDynamics365CRMCon.ContactForm1.SEND1.Click("37;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(6));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\n                Dzieki\r\n            ') on item 'INKUBITMicrosoftDynamics365CRMCon.ContactForm1.DivTagDzieki'.", repo.INKUBITMicrosoftDynamics365CRMCon.ContactForm1.DivTagDziekiInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.ContactForm1.DivTagDziekiInfo, "InnerText", "\n                Dzieki\r\n            ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'INKUBITMicrosoftDynamics365CRMCon'.", repo.INKUBITMicrosoftDynamics365CRMCon.SelfInfo, new RecordItemIndex(8));
            Host.Current.CloseApplication(repo.INKUBITMicrosoftDynamics365CRMCon.Self, 1000);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://inkubit-test.crm4.dynamics.com' with browser 'Chrome' in normal mode.", new RecordItemIndex(9));
            Host.Current.OpenBrowser("https://inkubit-test.crm4.dynamics.com", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10ms.", new RecordItemIndex(10));
            Delay.Duration(10, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ButBegin' at Center.", repo.JobApplicationRanorex1RaTest.ButBeginInfo, new RecordItemIndex(11));
            repo.JobApplicationRanorex1RaTest.ButBegin.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsINKUBITDefaultDashboard.NavTabButtonArrowDownNavTabButtonImageS' at Center.", repo.DashboardsINKUBITDefaultDashboard.NavTabButtonArrowDownNavTabButtonImageSInfo, new RecordItemIndex(12));
            repo.DashboardsINKUBITDefaultDashboard.NavTabButtonArrowDownNavTabButtonImageS.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(13));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.NavActivities' at 161;8.", repo.JobApplicationRanorex1RaTest.NavActivitiesInfo, new RecordItemIndex(14));
            repo.JobApplicationRanorex1RaTest.NavActivities.Click("161;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(15));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.SelectAView' at 14;9.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.SelectAViewInfo, new RecordItemIndex(16));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.SelectAView.Click("14;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(17));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.HttpsInkubitTestCrm4DynamicsCom' at 1;15.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.HttpsInkubitTestCrm4DynamicsComInfo, new RecordItemIndex(18));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.HttpsInkubitTestCrm4DynamicsCom.Click("1;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(19));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTest' at 50;8.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTestInfo, new RecordItemIndex(20));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.RanorexTest.Click("50;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(21));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Ref - Test3') on item 'JobApplicationRanorex1RaTest.ContentIFrame0.RefTest3'.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.RefTest3Info, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.JobApplicationRanorex1RaTest.ContentIFrame0.RefTest3Info, "InnerText", "Ref - Test3");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ContentIFrame0.ATag1227201865244PMRanorexStudi' at 75;13.", repo.JobApplicationRanorex1RaTest.ContentIFrame0.ATag1227201865244PMRanorexStudiInfo, new RecordItemIndex(23));
            repo.JobApplicationRanorex1RaTest.ContentIFrame0.ATag1227201865244PMRanorexStudi.Click("75;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(24));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.SpanTagDelete1' at 16;10.", repo.JobApplicationRanorex1RaTest.SpanTagDelete1Info, new RecordItemIndex(25));
            repo.JobApplicationRanorex1RaTest.SpanTagDelete1.Click("16;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.DivTagDelete' at Center.", repo.JobApplicationRanorex1RaTest.DivTagDeleteInfo, new RecordItemIndex(26));
            repo.JobApplicationRanorex1RaTest.DivTagDelete.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(27));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'JobApplicationRanorex1RaTest'.", repo.JobApplicationRanorex1RaTest.SelfInfo, new RecordItemIndex(28));
            Host.Current.CloseApplication(repo.JobApplicationRanorex1RaTest.Self, 1000);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
