///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace INKUBIT_Test___ContactForm
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PowerBIallaroundMicrosoftDynamics365 recording.
    /// </summary>
    [TestModule("1cf75c84-82c3-4139-9662-f84390bf36e2", ModuleType.Recording, 1)]
    public partial class PowerBIallaroundMicrosoftDynamics365 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the INKUBIT_Test___ContactFormRepository repository.
        /// </summary>
        public static INKUBIT_Test___ContactFormRepository repo = INKUBIT_Test___ContactFormRepository.Instance;

        static PowerBIallaroundMicrosoftDynamics365 instance = new PowerBIallaroundMicrosoftDynamics365();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PowerBIallaroundMicrosoftDynamics365()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PowerBIallaroundMicrosoftDynamics365 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.inkubit.com/en-us/blog/microsoft-dynamics-365/power-bi-all-around-microsoft-dynamics-365/' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://www.inkubit.com/en-us/blog/microsoft-dynamics-365/power-bi-all-around-microsoft-dynamics-365/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='In the past few years, there have been no real changes in the diagram solution until Microsoft Dynamics CRM 2016 was introduced. With Power BI, on the other hand, we have now the possibility to draw data from hundreds of sources and visualize them for users in an individual way. For Office 365, this cloud service is now fully compatible with . This makes it possible to create comprehensive analyzes in the customer engagement environment as well.') on item 'HttpsWwwInkubitComEnUsCareers.InThePastFewYearsThereHaveBeenN'.", repo.HttpsWwwInkubitComEnUsCareers.InThePastFewYearsThereHaveBeenNInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.InThePastFewYearsThereHaveBeenNInfo, "InnerText", "In the past few years, there have been no real changes in the diagram solution until Microsoft Dynamics CRM 2016 was introduced. With Power BI, on the other hand, we have now the possibility to draw data from hundreds of sources and visualize them for users in an individual way. For Office 365, this cloud service is now fully compatible with . This makes it possible to create comprehensive analyzes in the customer engagement environment as well.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Power BI all around Microsoft Dynamics 365') on item 'HttpsWwwInkubitComEnUsCareers.PowerBIAllAroundMicrosoftDynamics3'.", repo.HttpsWwwInkubitComEnUsCareers.PowerBIAllAroundMicrosoftDynamics3Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.PowerBIAllAroundMicrosoftDynamics3Info, "InnerText", "Power BI all around Microsoft Dynamics 365");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='h1') on item 'HttpsWwwInkubitComEnUsCareers.PowerBIAllAroundMicrosoftDynamics3'.", repo.HttpsWwwInkubitComEnUsCareers.PowerBIAllAroundMicrosoftDynamics3Info, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.PowerBIAllAroundMicrosoftDynamics3Info, "TagName", "h1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwInkubitComEnUsCareers.Submenu' at 14;21.", repo.HttpsWwwInkubitComEnUsCareers.SubmenuInfo, new RecordItemIndex(4));
            repo.HttpsWwwInkubitComEnUsCareers.Submenu.Click("14;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend1' at 7;6.", repo.HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend1Info, new RecordItemIndex(5));
            repo.HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend1.Click("7;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='In den letzten Jahren gab es in der hauseigenen Diagramm Lösung bis Microsoft  nur wenige Änderungen. Mit Power BI hingegen besteht jetzt die Möglichkeit Daten aus hunderten von Quellen zu ziehen und auf den Nutzer maßgeschneidert zu visualisieren. Für Office 365 ist dieser Cloud Service seit neusten vollständig kompatibel mit Microsoft Dynamics 365. Hiermit ist es möglich auch im Customer Engagement Umfeld umfangreiche Analysen zu erstellen.') on item 'HttpsWwwInkubitComEnUsCareers.InDenLetztenJahrenGabEsInDerHaus'.", repo.HttpsWwwInkubitComEnUsCareers.InDenLetztenJahrenGabEsInDerHausInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.InDenLetztenJahrenGabEsInDerHausInfo, "InnerText", "In den letzten Jahren gab es in der hauseigenen Diagramm Lösung bis Microsoft  nur wenige Änderungen. Mit Power BI hingegen besteht jetzt die Möglichkeit Daten aus hunderten von Quellen zu ziehen und auf den Nutzer maßgeschneidert zu visualisieren. Für Office 365 ist dieser Cloud Service seit neusten vollständig kompatibel mit Microsoft Dynamics 365. Hiermit ist es möglich auch im Customer Engagement Umfeld umfangreiche Analysen zu erstellen.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwInkubitComEnUsCareers.Submenu' at 11;21.", repo.HttpsWwwInkubitComEnUsCareers.SubmenuInfo, new RecordItemIndex(7));
            repo.HttpsWwwInkubitComEnUsCareers.Submenu.Click("11;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend2' at 7;11.", repo.HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend2Info, new RecordItemIndex(8));
            repo.HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend2.Click("7;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='In the past few years, there have been no real changes in the diagram solution until Microsoft Dynamics CRM 2016 was introduced. With Power BI, on the other hand, we have now the possibility to draw data from hundreds of sources and visualize them for users in an individual way. For Office 365, this cloud service is now fully compatible with . This makes it possible to create comprehensive analyzes in the customer engagement environment as well.') on item 'HttpsWwwInkubitComEnUsCareers.InThePastFewYearsThereHaveBeenN'.", repo.HttpsWwwInkubitComEnUsCareers.InThePastFewYearsThereHaveBeenNInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.InThePastFewYearsThereHaveBeenNInfo, "InnerText", "In the past few years, there have been no real changes in the diagram solution until Microsoft Dynamics CRM 2016 was introduced. With Power BI, on the other hand, we have now the possibility to draw data from hundreds of sources and visualize them for users in an individual way. For Office 365, this cloud service is now fully compatible with . This makes it possible to create comprehensive analyzes in the customer engagement environment as well.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'HttpsWwwInkubitComEnUsCareers'.", repo.HttpsWwwInkubitComEnUsCareers.SelfInfo, new RecordItemIndex(10));
            Host.Current.CloseApplication(repo.HttpsWwwInkubitComEnUsCareers.Self, 100);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
