///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace INKUBIT_Test___ContactForm
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("8c3c4f55-3adb-4813-9000-57a51b8521a7", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the INKUBIT_Test___ContactFormRepository repository.
        /// </summary>
        public static INKUBIT_Test___ContactFormRepository repo = INKUBIT_Test___ContactFormRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://test.inkubit.com/en-us/careers/' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://test.inkubit.com/en-us/careers/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'INKUBITMicrosoftDynamics365CRMCon.SeniorMicrosoftDynamics365Consultan'.", repo.INKUBITMicrosoftDynamics365CRMCon.SeniorMicrosoftDynamics365ConsultanInfo, new RecordItemIndex(2));
            Validate.Exists(repo.INKUBITMicrosoftDynamics365CRMCon.SeniorMicrosoftDynamics365ConsultanInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(3));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'INKUBITMicrosoftDynamics365CRMCon.PanelBody.SeniorSAPHCMConsultant'.", repo.INKUBITMicrosoftDynamics365CRMCon.PanelBody.SeniorSAPHCMConsultantInfo, new RecordItemIndex(4));
            Validate.Exists(repo.INKUBITMicrosoftDynamics365CRMCon.PanelBody.SeniorSAPHCMConsultantInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'INKUBITMicrosoftDynamics365CRMCon.PanelBody.SAPSeniorBusinessIntelligenceConsult'.", repo.INKUBITMicrosoftDynamics365CRMCon.PanelBody.SAPSeniorBusinessIntelligenceConsultInfo, new RecordItemIndex(5));
            Validate.Exists(repo.INKUBITMicrosoftDynamics365CRMCon.PanelBody.SAPSeniorBusinessIntelligenceConsultInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'INKUBITMicrosoftDynamics365CRMCon.PanelBody.SAPSeniorBankingConsultant'.", repo.INKUBITMicrosoftDynamics365CRMCon.PanelBody.SAPSeniorBankingConsultantInfo, new RecordItemIndex(6));
            Validate.Exists(repo.INKUBITMicrosoftDynamics365CRMCon.PanelBody.SAPSeniorBankingConsultantInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.SeniorMicrosoftDynamics365Consultan' at 89;7.", repo.INKUBITMicrosoftDynamics365CRMCon.SeniorMicrosoftDynamics365ConsultanInfo, new RecordItemIndex(7));
            repo.INKUBITMicrosoftDynamics365CRMCon.SeniorMicrosoftDynamics365Consultan.Click("89;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(8));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1080 units.", new RecordItemIndex(9));
            Mouse.ScrollWheel(-1080);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.DivTag' at 93;34.", repo.INKUBITMicrosoftDynamics365CRMCon.DivTagInfo, new RecordItemIndex(10));
            repo.INKUBITMicrosoftDynamics365CRMCon.DivTag.Click("93;34");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.FirstName' at 223;20.", repo.INKUBITMicrosoftDynamics365CRMCon.FirstNameInfo, new RecordItemIndex(11));
            repo.INKUBITMicrosoftDynamics365CRMCon.FirstName.Click("223;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ranorex1' with focus on 'INKUBITMicrosoftDynamics365CRMCon.FirstName'.", repo.INKUBITMicrosoftDynamics365CRMCon.FirstNameInfo, new RecordItemIndex(12));
            repo.INKUBITMicrosoftDynamics365CRMCon.FirstName.PressKeys("ranorex1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.LastName' at 220;35.", repo.INKUBITMicrosoftDynamics365CRMCon.LastNameInfo, new RecordItemIndex(13));
            repo.INKUBITMicrosoftDynamics365CRMCon.LastName.Click("220;35");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ra' with focus on 'INKUBITMicrosoftDynamics365CRMCon.LastName'.", repo.INKUBITMicrosoftDynamics365CRMCon.LastNameInfo, new RecordItemIndex(14));
            repo.INKUBITMicrosoftDynamics365CRMCon.LastName.PressKeys("ra");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Email' at 182;17.", repo.INKUBITMicrosoftDynamics365CRMCon.EmailInfo, new RecordItemIndex(15));
            repo.INKUBITMicrosoftDynamics365CRMCon.Email.Click("182;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '123{RShiftKey down}@{RShiftKey up}123.pl' with focus on 'INKUBITMicrosoftDynamics365CRMCon.Email'.", repo.INKUBITMicrosoftDynamics365CRMCon.EmailInfo, new RecordItemIndex(16));
            repo.INKUBITMicrosoftDynamics365CRMCon.Email.PressKeys("123{RShiftKey down}@{RShiftKey up}123.pl");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.PhoneNumber' at 181;29.", repo.INKUBITMicrosoftDynamics365CRMCon.PhoneNumberInfo, new RecordItemIndex(17));
            repo.INKUBITMicrosoftDynamics365CRMCon.PhoneNumber.Click("181;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '666677' with focus on 'INKUBITMicrosoftDynamics365CRMCon.PhoneNumber'.", repo.INKUBITMicrosoftDynamics365CRMCon.PhoneNumberInfo, new RecordItemIndex(18));
            repo.INKUBITMicrosoftDynamics365CRMCon.PhoneNumber.PressKeys("666677");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.InputJobapplication' at 46;19.", repo.INKUBITMicrosoftDynamics365CRMCon.InputJobapplicationInfo, new RecordItemIndex(19));
            repo.INKUBITMicrosoftDynamics365CRMCon.InputJobapplication.Click("46;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.ThisPC' at 16;4.", repo.Open.ThisPCInfo, new RecordItemIndex(20));
            repo.Open.ThisPC.Click("16;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Open.SystemItemNameDisplay' at 41;3.", repo.Open.SystemItemNameDisplayInfo, new RecordItemIndex(21));
            repo.Open.SystemItemNameDisplay.DoubleClick("41;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Open.SystemItemNameDisplay1' at 60;14.", repo.Open.SystemItemNameDisplay1Info, new RecordItemIndex(22));
            repo.Open.SystemItemNameDisplay1.DoubleClick("60;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Open.SystemItemNameDisplay2' at 6;11.", repo.Open.SystemItemNameDisplay2Info, new RecordItemIndex(23));
            repo.Open.SystemItemNameDisplay2.DoubleClick("6;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Path' at UpperCenter.", repo.INKUBITMicrosoftDynamics365CRMCon.PathInfo, new RecordItemIndex(24));
            repo.INKUBITMicrosoftDynamics365CRMCon.Path.Click(Location.UpperCenter);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(25));
            Delay.Duration(10000, false);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Your job application has been delivered successfully. Thank you very much! We will respond within a short time!') on item 'INKUBITMicrosoftDynamics365CRMCon.JobAnnouncementNotificationDiv'.", repo.INKUBITMicrosoftDynamics365CRMCon.JobAnnouncementNotificationDivInfo, new RecordItemIndex(26));
                Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.JobAnnouncementNotificationDivInfo, "InnerText", "Your job application has been delivered successfully. Thank you very much! We will respond within a short time!", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(26)); }
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://inkubit-test.crm4.dynamics.com/' with browser 'Chrome' in normal mode.", new RecordItemIndex(27));
            Host.Current.OpenBrowser("https://inkubit-test.crm4.dynamics.com/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 15s.", new RecordItemIndex(28));
            Delay.Duration(15000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsINKUBITDefaultDashboard.ButBegin' at 41;13.", repo.DashboardsINKUBITDefaultDashboard.ButBeginInfo, new RecordItemIndex(29));
            repo.DashboardsINKUBITDefaultDashboard.ButBegin.Click("41;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(30));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsINKUBITDefaultDashboard.NavTabButtonArrowDownNavTabButtonImageS' at 17;6.", repo.DashboardsINKUBITDefaultDashboard.NavTabButtonArrowDownNavTabButtonImageSInfo, new RecordItemIndex(31));
            repo.DashboardsINKUBITDefaultDashboard.NavTabButtonArrowDownNavTabButtonImageS.Click("17;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(32));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsINKUBITDefaultDashboard.CoreSolutions' at 58;43.", repo.DashboardsINKUBITDefaultDashboard.CoreSolutionsInfo, new RecordItemIndex(33));
            repo.DashboardsINKUBITDefaultDashboard.CoreSolutions.Click("58;43");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(34));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsINKUBITDefaultDashboard.HttpsInkubitTestCrm4DynamicsComP' at 14;17.", repo.DashboardsINKUBITDefaultDashboard.HttpsInkubitTestCrm4DynamicsComPInfo, new RecordItemIndex(35));
            repo.DashboardsINKUBITDefaultDashboard.HttpsInkubitTestCrm4DynamicsComP.Click("14;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(36));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationsActiveJobApplications.JobApplicationNo' at 99;12.", repo.JobApplicationsActiveJobApplications.JobApplicationNoInfo, new RecordItemIndex(37));
            repo.JobApplicationsActiveJobApplications.JobApplicationNo.Click("99;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationsActiveJobApplications.JobApplicationNo' at 99;12.", repo.JobApplicationsActiveJobApplications.JobApplicationNoInfo, new RecordItemIndex(38));
            repo.JobApplicationsActiveJobApplications.JobApplicationNo.Click("99;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'JobApplicationsActiveJobApplications.Ranorex1RaTest'.", repo.JobApplicationsActiveJobApplications.Ranorex1RaTestInfo, new RecordItemIndex(39));
            Validate.Exists(repo.JobApplicationsActiveJobApplications.Ranorex1RaTestInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'JobApplicationsActiveJobApplications.Ranorex1RaTest' at 73;9.", repo.JobApplicationsActiveJobApplications.Ranorex1RaTestInfo, new RecordItemIndex(40));
            repo.JobApplicationsActiveJobApplications.Ranorex1RaTest.MoveTo("73;9");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationsActiveJobApplications.Ranorex1RaTest' at 51;7.", repo.JobApplicationsActiveJobApplications.Ranorex1RaTestInfo, new RecordItemIndex(41));
            repo.JobApplicationsActiveJobApplications.Ranorex1RaTest.Click("51;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(42));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.NOTES' at 144;22.", repo.JobApplicationRanorex1RaTest.NOTESInfo, new RecordItemIndex(43));
            repo.JobApplicationRanorex1RaTest.NOTES.Click("144;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>' test.pdf ') on item 'JobApplicationRanorex1RaTest.ContentIFrame1.TestPdf2'.", repo.JobApplicationRanorex1RaTest.ContentIFrame1.TestPdf2Info, new RecordItemIndex(44));
            Validate.AttributeContains(repo.JobApplicationRanorex1RaTest.ContentIFrame1.TestPdf2Info, "InnerText", " test.pdf ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.SpanTagDelete' at 6;8.", repo.JobApplicationRanorex1RaTest.SpanTagDeleteInfo, new RecordItemIndex(45));
            repo.JobApplicationRanorex1RaTest.SpanTagDelete.Click("6;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JobApplicationRanorex1RaTest.ButBegin' at 38;21.", repo.JobApplicationRanorex1RaTest.ButBeginInfo, new RecordItemIndex(46));
            repo.JobApplicationRanorex1RaTest.ButBegin.Click("38;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(47));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'INKUBITMicrosoftDynamics365CRMCon'.", repo.INKUBITMicrosoftDynamics365CRMCon.SelfInfo, new RecordItemIndex(48));
            Host.Current.CloseApplication(repo.INKUBITMicrosoftDynamics365CRMCon.Self, 1000);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'JobApplicationsActiveJobApplications'.", repo.JobApplicationsActiveJobApplications.SelfInfo, new RecordItemIndex(49));
            Host.Current.CloseApplication(repo.JobApplicationsActiveJobApplications.Self, 1000);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
