///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace INKUBIT_Test___ContactForm
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ThebenefitsofvirtualentitiesinMicrosoftDynamics365 recording.
    /// </summary>
    [TestModule("8d16ca71-c7ad-4e1f-bcb1-0ef1e0d02fd3", ModuleType.Recording, 1)]
    public partial class ThebenefitsofvirtualentitiesinMicrosoftDynamics365 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the INKUBIT_Test___ContactFormRepository repository.
        /// </summary>
        public static INKUBIT_Test___ContactFormRepository repo = INKUBIT_Test___ContactFormRepository.Instance;

        static ThebenefitsofvirtualentitiesinMicrosoftDynamics365 instance = new ThebenefitsofvirtualentitiesinMicrosoftDynamics365();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ThebenefitsofvirtualentitiesinMicrosoftDynamics365()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ThebenefitsofvirtualentitiesinMicrosoftDynamics365 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.inkubit.com/en-us/blog/microsoft-dynamics-365/the-benefits-of-virtual-entities-in-microsoft-dynamics-365/' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://www.inkubit.com/en-us/blog/microsoft-dynamics-365/the-benefits-of-virtual-entities-in-microsoft-dynamics-365/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Microsoft continues to succeed in unlocking parts of what used to be a developer-only world for less-advanced consultants. would be a great example of how to simplify developer work. With the virtual entity released since version 9.0, it is now possible to further reduce efforts in projects.') on item 'HttpsWwwInkubitComEnUsCareers.MicrosoftContinuesToSucceedInUnlock'.", repo.HttpsWwwInkubitComEnUsCareers.MicrosoftContinuesToSucceedInUnlockInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.MicrosoftContinuesToSucceedInUnlockInfo, "InnerText", "Microsoft continues to succeed in unlocking parts of what used to be a developer-only world for less-advanced consultants. would be a great example of how to simplify developer work. With the virtual entity released since version 9.0, it is now possible to further reduce efforts in projects.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='The benefits of virtual entities in Microsoft Dynamics 365') on item 'HttpsWwwInkubitComEnUsCareers.TheBenefitsOfVirtualEntitiesInMicr'.", repo.HttpsWwwInkubitComEnUsCareers.TheBenefitsOfVirtualEntitiesInMicrInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.TheBenefitsOfVirtualEntitiesInMicrInfo, "InnerText", "The benefits of virtual entities in Microsoft Dynamics 365");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='h1') on item 'HttpsWwwInkubitComEnUsCareers.TheBenefitsOfVirtualEntitiesInMicr'.", repo.HttpsWwwInkubitComEnUsCareers.TheBenefitsOfVirtualEntitiesInMicrInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.TheBenefitsOfVirtualEntitiesInMicrInfo, "TagName", "h1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwInkubitComEnUsCareers.Submenu' at 15;20.", repo.HttpsWwwInkubitComEnUsCareers.SubmenuInfo, new RecordItemIndex(4));
            repo.HttpsWwwInkubitComEnUsCareers.Submenu.Click("15;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend1' at 4;1.", repo.HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend1Info, new RecordItemIndex(5));
            repo.HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend1.Click("4;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Microsoft schafft es weiterhin mit Erfolg Teile der früher nur für Entwickler erreichbaren Welt für weniger technisch begabte Consultants freizuschalten. wäre hier ein hervorragendes Bespiel wie man die Entwicklerarbeit vereinfachen kann. Mit der seit der Version 9.0 freigeschalteten virtuellen Entität wird es nun möglich Aufwände in Projekten weiter zu verringern.') on item 'HttpsWwwInkubitComEnUsCareers.MicrosoftSchafftEsWeiterhinMitErfol'.", repo.HttpsWwwInkubitComEnUsCareers.MicrosoftSchafftEsWeiterhinMitErfolInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.MicrosoftSchafftEsWeiterhinMitErfolInfo, "InnerText", "Microsoft schafft es weiterhin mit Erfolg Teile der früher nur für Entwickler erreichbaren Welt für weniger technisch begabte Consultants freizuschalten. wäre hier ein hervorragendes Bespiel wie man die Entwicklerarbeit vereinfachen kann. Mit der seit der Version 9.0 freigeschalteten virtuellen Entität wird es nun möglich Aufwände in Projekten weiter zu verringern.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwInkubitComEnUsCareers.Submenu' at 11;21.", repo.HttpsWwwInkubitComEnUsCareers.SubmenuInfo, new RecordItemIndex(7));
            repo.HttpsWwwInkubitComEnUsCareers.Submenu.Click("11;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend2' at 4;2.", repo.HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend2Info, new RecordItemIndex(8));
            repo.HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend2.Click("4;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Microsoft continues to succeed in unlocking parts of what used to be a developer-only world for less-advanced consultants. would be a great example of how to simplify developer work. With the virtual entity released since version 9.0, it is now possible to further reduce efforts in projects.') on item 'HttpsWwwInkubitComEnUsCareers.MicrosoftContinuesToSucceedInUnlock'.", repo.HttpsWwwInkubitComEnUsCareers.MicrosoftContinuesToSucceedInUnlockInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.MicrosoftContinuesToSucceedInUnlockInfo, "InnerText", "Microsoft continues to succeed in unlocking parts of what used to be a developer-only world for less-advanced consultants. would be a great example of how to simplify developer work. With the virtual entity released since version 9.0, it is now possible to further reduce efforts in projects.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'HttpsWwwInkubitComEnUsCareers'.", repo.HttpsWwwInkubitComEnUsCareers.SelfInfo, new RecordItemIndex(10));
            Host.Current.CloseApplication(repo.HttpsWwwInkubitComEnUsCareers.Self, 100);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
