///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace INKUBIT_Test___ContactForm
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TheLicenseGuideforMicrosoftDynamics365 recording.
    /// </summary>
    [TestModule("c269ee76-4e37-4e74-a720-076c6de5b04a", ModuleType.Recording, 1)]
    public partial class TheLicenseGuideforMicrosoftDynamics365 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the INKUBIT_Test___ContactFormRepository repository.
        /// </summary>
        public static INKUBIT_Test___ContactFormRepository repo = INKUBIT_Test___ContactFormRepository.Instance;

        static TheLicenseGuideforMicrosoftDynamics365 instance = new TheLicenseGuideforMicrosoftDynamics365();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TheLicenseGuideforMicrosoftDynamics365()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TheLicenseGuideforMicrosoftDynamics365 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.inkubit.com/blog/microsoft-dynamics-365/the-license-guide-for-microsoft-dynamics-365/' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://www.inkubit.com/blog/microsoft-dynamics-365/the-license-guide-for-microsoft-dynamics-365/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Licensing for Microsoft Dynamics 365 products can be very confusing for a lot of people, particularly at the beginning. Especially because Microsoft Dynamics 365 collects a large number of different applications under a uniform name. It is possible to divide roughly the applications into two parts - ERP (Enterprise Resource Planning) and . In the following blog article, we would like to go into more detail about licensing in the area of CRM. Applications that are collected under the term Microsoft Dynamics 365 Customer Engagement. Are you already confused? If yes, read on to get some clarity.') on item 'HttpsWwwInkubitComEnUsCareers.LicensingForMicrosoftDynamics365Pro'.", repo.HttpsWwwInkubitComEnUsCareers.LicensingForMicrosoftDynamics365ProInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.LicensingForMicrosoftDynamics365ProInfo, "InnerText", "Licensing for Microsoft Dynamics 365 products can be very confusing for a lot of people, particularly at the beginning. Especially because Microsoft Dynamics 365 collects a large number of different applications under a uniform name. It is possible to divide roughly the applications into two parts - ERP (Enterprise Resource Planning) and . In the following blog article, we would like to go into more detail about licensing in the area of CRM. Applications that are collected under the term Microsoft Dynamics 365 Customer Engagement. Are you already confused? If yes, read on to get some clarity.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='The License Guide for Microsoft Dynamics 365') on item 'HttpsWwwInkubitComEnUsCareers.TheLicenseGuideForMicrosoftDynamics'.", repo.HttpsWwwInkubitComEnUsCareers.TheLicenseGuideForMicrosoftDynamicsInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.TheLicenseGuideForMicrosoftDynamicsInfo, "InnerText", "The License Guide for Microsoft Dynamics 365");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend' at 3;5.", repo.HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontendInfo, new RecordItemIndex(3));
            repo.HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend.Click("3;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend1' at 7;10.", repo.HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend1Info, new RecordItemIndex(4));
            repo.HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend1.Click("7;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Die Lizenzierung für Microsoft Dynamics 365 Produkte kann für viele zu Beginn sehr verwirrend sein. Zumal Microsoft Dynamics 365 eine vielzahl von verschiedenen Applikationen unter einer einheitlichen Bezeichnung sammelt. Grob aufteilen könnte man die Applikationen in zwei Teilbereiche – ERP (Enterprise Resource Planning) und CRM (Customer Relationship Management). Wir möchten in dem folgenden Blog Artikel näher auf die Lizenzierung im Bereich  eingehen. Also Applikationen die unter dem Begriff Microsoft Dynamics 365 Customer Engagement gesammelt werden. Sind Sie bereits verwirrt? Falls ja, lesen Sie weiter um sich Klarheiten zu verschaffen.') on item 'HttpsWwwInkubitComEnUsCareers.DieLizenzierungFuerMicrosoftDynamics'.", repo.HttpsWwwInkubitComEnUsCareers.DieLizenzierungFuerMicrosoftDynamicsInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.DieLizenzierungFuerMicrosoftDynamicsInfo, "InnerText", "Die Lizenzierung für Microsoft Dynamics 365 Produkte kann für viele zu Beginn sehr verwirrend sein. Zumal Microsoft Dynamics 365 eine vielzahl von verschiedenen Applikationen unter einer einheitlichen Bezeichnung sammelt. Grob aufteilen könnte man die Applikationen in zwei Teilbereiche – ERP (Enterprise Resource Planning) und CRM (Customer Relationship Management). Wir möchten in dem folgenden Blog Artikel näher auf die Lizenzierung im Bereich  eingehen. Also Applikationen die unter dem Begriff Microsoft Dynamics 365 Customer Engagement gesammelt werden. Sind Sie bereits verwirrt? Falls ja, lesen Sie weiter um sich Klarheiten zu verschaffen.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Der Guide für Microsoft Dynamics 365 Lizenzen') on item 'HttpsWwwInkubitComEnUsCareers.DerGuideFuerMicrosoftDynamics365Li'.", repo.HttpsWwwInkubitComEnUsCareers.DerGuideFuerMicrosoftDynamics365LiInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.DerGuideFuerMicrosoftDynamics365LiInfo, "InnerText", "Der Guide für Microsoft Dynamics 365 Lizenzen");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwInkubitComEnUsCareers.Submenu' at 11;20.", repo.HttpsWwwInkubitComEnUsCareers.SubmenuInfo, new RecordItemIndex(7));
            repo.HttpsWwwInkubitComEnUsCareers.Submenu.Click("11;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend2' at 4;1.", repo.HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend2Info, new RecordItemIndex(8));
            repo.HttpsWwwInkubitComEnUsCareers.HttpsWwwInkubitComAssetsFrontend2.Click("4;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Licensing for Microsoft Dynamics 365 products can be very confusing for a lot of people, particularly at the beginning. Especially because Microsoft Dynamics 365 collects a large number of different applications under a uniform name. It is possible to divide roughly the applications into two parts - ERP (Enterprise Resource Planning) and . In the following blog article, we would like to go into more detail about licensing in the area of CRM. Applications that are collected under the term Microsoft Dynamics 365 Customer Engagement. Are you already confused? If yes, read on to get some clarity.') on item 'HttpsWwwInkubitComEnUsCareers.LicensingForMicrosoftDynamics365Pro'.", repo.HttpsWwwInkubitComEnUsCareers.LicensingForMicrosoftDynamics365ProInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.HttpsWwwInkubitComEnUsCareers.LicensingForMicrosoftDynamics365ProInfo, "InnerText", "Licensing for Microsoft Dynamics 365 products can be very confusing for a lot of people, particularly at the beginning. Especially because Microsoft Dynamics 365 collects a large number of different applications under a uniform name. It is possible to divide roughly the applications into two parts - ERP (Enterprise Resource Planning) and . In the following blog article, we would like to go into more detail about licensing in the area of CRM. Applications that are collected under the term Microsoft Dynamics 365 Customer Engagement. Are you already confused? If yes, read on to get some clarity.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'HttpsWwwInkubitComEnUsCareers'.", repo.HttpsWwwInkubitComEnUsCareers.SelfInfo, new RecordItemIndex(10));
            Host.Current.CloseApplication(repo.HttpsWwwInkubitComEnUsCareers.Self, 100);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
