///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ranorex_Automation_Helpers
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Ranorex_Automation_HelpersRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("a8e4f482-3ad7-4de1-b09a-2e420606ad1b")]
    public partial class Ranorex_Automation_HelpersRepository : RepoGenBaseFolder
    {
        static Ranorex_Automation_HelpersRepository instance = new Ranorex_Automation_HelpersRepository();

        /// <summary>
        /// Gets the singleton class instance representing the Ranorex_Automation_HelpersRepository element repository.
        /// </summary>
        [RepositoryFolder("a8e4f482-3ad7-4de1-b09a-2e420606ad1b")]
        public static Ranorex_Automation_HelpersRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Ranorex_Automation_HelpersRepository() 
            : base("Ranorex_Automation_HelpersRepository", "/", null, 0, false, "a8e4f482-3ad7-4de1-b09a-2e420606ad1b", ".\\RepositoryImages\\Ranorex_Automation_HelpersRepositorya8e4f482.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a8e4f482-3ad7-4de1-b09a-2e420606ad1b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class Ranorex_Automation_HelpersRepositoryFolders
    {
    }
#pragma warning restore 0436
}