///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace test2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the test2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("cfbf26c1-a683-4a11-a758-6ec84567665f")]
    public partial class test2Repository : RepoGenBaseFolder
    {
        static test2Repository instance = new test2Repository();

        /// <summary>
        /// Gets the singleton class instance representing the test2Repository element repository.
        /// </summary>
        [RepositoryFolder("cfbf26c1-a683-4a11-a758-6ec84567665f")]
        public static test2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public test2Repository() 
            : base("test2Repository", "/", null, 0, false, "cfbf26c1-a683-4a11-a758-6ec84567665f", ".\\RepositoryImages\\test2Repositorycfbf26c1.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("cfbf26c1-a683-4a11-a758-6ec84567665f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class test2RepositoryFolders
    {
    }
#pragma warning restore 0436
}